# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='m',
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
