# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20170601_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
