# Generated by Django 2.0 on 2017-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
