# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='m',
            field=models.ManyToManyField(to='app01.Host'),
        ),
    ]
