# Generated by Django 2.0 on 2017-05-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='NewBook',
        ),
    ]
