# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_firm_host_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
